version: '3.8'

services:
  # 基础环境（快速启动）
  biomni-basic:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: biomni-basic
    ports:
      - "0.0.0.0:8888:8888"  # Jupyter notebook
      - "0.0.0.0:7860:7860"  # Gradio
    volumes:
      - ./data:/opt/biomni/data
      - ./notebooks:/opt/biomni/notebooks
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
    command: >
      bash -c "
        echo 'Starting Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' &
        echo 'Starting Gradio App...' &&
        python /opt/biomni/gradio_app.py &
        echo 'Services started. Switching to biomni user...' &&
        exec gosu biomni bash
      "
    networks:
      - biomni-network
    profiles:
      - basic

  # 完整环境（包含所有生物信息学工具）
  biomni-full:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biomni-full
    ports:
      - "0.0.0.0:8889:8888"  # Jupyter notebook
      - "0.0.0.0:7861:7860"  # Gradio
    volumes:
      - ./data:/opt/biomni/data
      - ./notebooks:/opt/biomni/notebooks
      - ./results:/opt/biomni/results
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
    command: >
      bash -c "
        echo 'Starting Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' &
        echo 'Starting Gradio App...' &&
        python /opt/biomni/gradio_app.py &
        wait
      "
    networks:
      - biomni-network
    profiles:
      - full

  # 开发环境（挂载源代码）
  biomni-dev:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: biomni-dev
    ports:
      - "0.0.0.0:8890:8888"  # Jupyter notebook
      - "0.0.0.0:7862:7860"  # Gradio
    volumes:
      - ./data:/opt/biomni/data
      - ./notebooks:/opt/biomni/notebooks
      - ../:/opt/biomni/src  # 挂载源代码
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
    command: >
      bash -c "
        echo 'Starting Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' &
        echo 'Starting Gradio App...' &&
        python /opt/biomni/gradio_app.py &
        wait
      "
    networks:
      - biomni-network
    profiles:
      - dev

volumes:
  data:
  notebooks:
  results:

networks:
  biomni-network:
    driver: bridge 