#version: '3.8'

services:
  # 旧版本服务 - 使用虚拟环境
  biomni-basic:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: biomni-basic
    ports:
      - "0.0.0.0:8888:8888"  # Jupyter notebook
      - "0.0.0.0:7860:7860"  # Gradio
    volumes:
      - ../biomni:/opt/biomni/biomni
      - ../pyproject.toml:/opt/biomni/pyproject.toml
      - ../biomni_data:/opt/biomni/data:ro
      - ./scripts:/opt/biomni/scripts
      - ./notebooks:/opt/biomni/notebooks
      - ./downloads:/opt/biomni/downloads
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
    command: >
      bash -c "
        pip install -e /opt/biomni
        echo 'Starting Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --notebook-dir=/opt/biomni/notebooks &
        echo 'Starting Gradio App...' &&
        cd /opt/biomni && python scripts/gradio_app.py &
        echo 'Services started successfully!' &&
        echo 'Jupyter Notebook: http://0.0.0.0:8888' &&
        echo 'Gradio App: http://0.0.0.0:7860' &&
        wait
      "
    networks:
      - biomni-network
    profiles:
      - basic

  biomni-full:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biomni-full
    ports:
      - "0.0.0.0:8889:8888"  # Jupyter notebook
      - "0.0.0.0:7861:7860"  # Gradio
    volumes:
      - ../biomni:/opt/biomni/biomni
      - ../pyproject.toml:/opt/biomni/pyproject.toml
      - ../biomni_data:/opt/biomni/data:ro
      - ./scripts:/opt/biomni/scripts
      - ./notebooks:/opt/biomni/notebooks
      - ../test_results:/opt/biomni/results
      - ./downloads:/opt/biomni/downloads
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
    command: >
      bash -c "
        source /opt/biomni/venv/bin/activate
        pip install -e /opt/biomni

        echo 'Starting Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --notebook-dir=/opt/biomni/notebooks &
        echo 'Starting Gradio App...' &&
        cd /opt/biomni && python scripts/gradio_app.py &
        echo 'Services started successfully!' &&
        echo 'Jupyter Notebook: http://0.0.0.0:8889' &&
        echo 'Gradio App: http://0.0.0.0:7861' &&
        wait
      "
    networks:
      - biomni-network
    profiles:
      - full

  biomni-dev:
    build:
      context: .
      dockerfile: Dockerfile.basic
    container_name: biomni-dev
    ports:
      - "0.0.0.0:8890:8888"  # Jupyter notebook
      - "0.0.0.0:7862:7860"  # Gradio
    volumes:
      - ../biomni:/opt/biomni/biomni
      - ../pyproject.toml:/opt/biomni/pyproject.toml
      - ../biomni_data:/opt/biomni/data:ro
      - ./scripts:/opt/biomni/scripts
      - ./notebooks:/opt/biomni/notebooks
      - ./downloads:/opt/biomni/downloads
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
    command: >
      bash -c "
        pip install -e /opt/biomni
        echo 'Starting Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --notebook-dir=/opt/biomni/notebooks &
        echo 'Starting Gradio App...' &&
        cd /opt/biomni && python scripts/gradio_app.py &
        echo 'Services started successfully!' &&
        echo 'Jupyter Notebook: http://0.0.0.0:8890' &&
        echo 'Gradio App: http://0.0.0.0:7862' &&
        wait
      "
    networks:
      - biomni-network
    profiles:
      - dev

  # 新版本服务 - 使用conda环境
  biomni-basic.1:
    build:
      context: .
      dockerfile: Dockerfile.basic.1
    container_name: biomni-basic.1
    ports:
      - "0.0.0.0:9998:8888"  # Jupyter notebook (避免端口冲突)
      - "0.0.0.0:9860:7860"  # Gradio
    volumes:
      - ../biomni:/opt/biomni/biomni
      - ../pyproject.toml:/opt/biomni/pyproject.toml
      - ../biomni_data:/opt/biomni/data:ro
      - ./scripts:/opt/biomni/scripts
      - biomni_cache:/home/biomni/.cache
      - ./notebooks:/opt/biomni/notebooks
      - ./downloads:/opt/biomni/downloads
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
      - PYTHONPATH=/opt/biomni
    command: >
      bash -c "
        echo '激活conda环境...' &&
        source /opt/miniconda3/etc/profile.d/conda.sh &&
        conda activate biomni_e1 &&
        echo '安装biomni包...' &&
        cd /opt/biomni &&
        pip install -e . &&
        echo '启动Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --notebook-dir=/opt/biomni/notebooks &
        echo '启动Gradio App...' &&
        cd /opt/biomni && python scripts/gradio_app.py &
        echo '服务启动成功！' &&
        echo 'Jupyter Notebook: http://localhost:9998' &&
        echo 'Gradio App: http://localhost:9860' &&
        wait
      "
    networks:
      - biomni-network
    profiles:
      - basic.1
    restart: unless-stopped

  biomni-full.1:
    build:
      context: .
      dockerfile: Dockerfile.1
    container_name: biomni-full.1
    ports:
      - "0.0.0.0:9997:8888"  # Jupyter notebook (避免端口冲突)
      - "0.0.0.0:9861:7860"  # Gradio
    volumes:
      - ../biomni:/opt/biomni/biomni
      - ../pyproject.toml:/opt/biomni/pyproject.toml
      - ../biomni_data:/opt/biomni/data:ro
      - ./scripts:/opt/biomni/scripts
      - ../biomni_results:/opt/biomni/results
      - biomni_cache:/home/biomni/.cache
      - ./notebooks:/opt/biomni/notebooks
      - ./downloads:/opt/biomni/downloads
      - /data_A002:/data_A002:ro
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
      - PYTHONPATH=/opt/biomni
    command: >
      bash -c "
        echo '激活conda环境...' &&
        source /opt/miniconda3/etc/profile.d/conda.sh &&
        conda activate biomni_e1 &&
        echo '安装biomni包...' &&
        cd /opt/biomni &&
        pip install -e . &&
        echo '启动Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --notebook-dir=/opt/biomni/notebooks &
        echo '启动Gradio App...' &&
        cd /opt/biomni && python scripts/gradio_app.py &
        echo '服务启动成功！' &&
        echo 'Jupyter Notebook: http://localhost:9997' &&
        echo 'Gradio App: http://localhost:9861' &&
        echo 'HOMER路径: /opt/biomni_tools/homer' &&
        echo 'CLI工具路径: /opt/biomni_tools/bin' &&
        wait
      "
    networks:
      - biomni-network
    profiles:
      - full.1
    restart: unless-stopped

  biomni-dev.1:
    build:
      context: .
      dockerfile: Dockerfile.basic.1
    container_name: biomni-dev.1
    ports:
      - "0.0.0.0:9990:8888"  # Jupyter notebook (避免端口冲突)
      - "0.0.0.0:9862:7860"  # Gradio
    volumes:
      - ../biomni:/opt/biomni/biomni
      - ../pyproject.toml:/opt/biomni/pyproject.toml
      - ../biomni_data:/opt/biomni/data:ro
      - ./scripts:/opt/biomni/scripts
      - ./notebooks:/opt/biomni/notebooks
      - biomni_cache:/home/biomni/.cache
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_ALLOW_REMOTE_ACCESS=true
      - PYTHONPATH=/opt/biomni
    command: >
      bash -c "
        echo '激活conda环境...' &&
        source /opt/miniconda3/etc/profile.d/conda.sh &&
        conda activate biomni_e1 &&
        echo '安装biomni包（开发模式）...' &&
        cd /opt/biomni &&
        pip install -e . &&
        echo '启动Jupyter Notebook...' &&
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*' --notebook-dir=/opt/biomni/notebooks &
        echo '启动Gradio App...' &&
        cd /opt/biomni && python scripts/gradio_app.py &
        echo '服务启动成功！' &&
        echo 'Jupyter Notebook: http://localhost:9990' &&
        echo 'Gradio App: http://localhost:9862' &&
        echo '开发环境已就绪！' &&
        wait
      "
    networks:
      - biomni-network
    profiles:
      - dev.1
    restart: unless-stopped

  # biomni-setup.1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.1
  #   container_name: biomni-setup.1
  #   volumes:
  #     - ../:/opt/biomni
  #     - ../biomni_data:/opt/biomni/data:ro
  #     - ../biomni_results:/opt/biomni/results
  #     - biomni_cache:/home/biomni/.cache
  #   environment:
  #     - PYTHONPATH=/opt/biomni
  #     - NON_INTERACTIVE=1
  #   command: >
  #     bash -c "
  #       echo '开始设置Biomni环境...' &&
  #       cd /opt/biomni &&
  #       chmod +x biomni_env/setup.sh &&
  #       ./biomni_env/setup.sh &&
  #       echo '环境设置完成！' &&
  #       echo '您现在可以运行：' &&
  #       echo 'docker compose --profile basic.1 up' &&
  #       echo '或' &&
  #       echo 'docker compose --profile full.1 up' &&
  #       tail -f /dev/null
  #     "
  #   networks:
  #     - biomni-network
  #   profiles:
  #     - setup.1

volumes:
  data:
  notebooks:
  results:
  downloads:
  biomni_cache:
    driver: local

networks:
  biomni-network:
    driver: bridge